package be.labo.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.AlertMessage;
import be.labo.data.AuditAlert;
import be.labo.data.Event;
import be.labo.data.User;

/**
 * Class _Alert was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Alert extends CayenneDataObject {

    public static final String ALERT_EVENT_PROPERTY = "alertEvent";
    public static final String ALERT_MESSAGE_PROPERTY = "alertMessage";
    public static final String ALERTAUDIT_PROPERTY = "alertaudit";
    public static final String CLOSER_PROPERTY = "closer";

    public static final String ID_PK_COLUMN = "id";

    public void setAlertEvent(Event alertEvent) {
        setToOneTarget(ALERT_EVENT_PROPERTY, alertEvent, true);
    }

    public Event getAlertEvent() {
        return (Event)readProperty(ALERT_EVENT_PROPERTY);
    }


    public void addToAlertMessage(AlertMessage obj) {
        addToManyTarget(ALERT_MESSAGE_PROPERTY, obj, true);
    }
    public void removeFromAlertMessage(AlertMessage obj) {
        removeToManyTarget(ALERT_MESSAGE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AlertMessage> getAlertMessage() {
        return (List<AlertMessage>)readProperty(ALERT_MESSAGE_PROPERTY);
    }


    public void addToAlertaudit(AuditAlert obj) {
        addToManyTarget(ALERTAUDIT_PROPERTY, obj, true);
    }
    public void removeFromAlertaudit(AuditAlert obj) {
        removeToManyTarget(ALERTAUDIT_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AuditAlert> getAlertaudit() {
        return (List<AuditAlert>)readProperty(ALERTAUDIT_PROPERTY);
    }


    public void setCloser(User closer) {
        setToOneTarget(CLOSER_PROPERTY, closer, true);
    }

    public User getCloser() {
        return (User)readProperty(CLOSER_PROPERTY);
    }


}
