package be.labo.data.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Alert;
import be.labo.data.GroupOfUsers;
import be.labo.data.User;

/**
 * Class _AlertMessage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AlertMessage extends CayenneDataObject {

    public static final String RECEIVED_PROPERTY = "received";
    public static final String SENT_PROPERTY = "sent";
    public static final String VIA_PROPERTY = "via";
    public static final String ALERT_GROUP_PROPERTY = "alertGroup";
    public static final String ALERT_USER_PROPERTY = "alertUser";
    public static final String MESSAGE_ALERT_PROPERTY = "messageAlert";

    public static final String ID_PK_COLUMN = "id";

    public void setReceived(Date received) {
        writeProperty(RECEIVED_PROPERTY, received);
    }
    public Date getReceived() {
        return (Date)readProperty(RECEIVED_PROPERTY);
    }

    public void setSent(Date sent) {
        writeProperty(SENT_PROPERTY, sent);
    }
    public Date getSent() {
        return (Date)readProperty(SENT_PROPERTY);
    }

    public void setVia(Byte via) {
        writeProperty(VIA_PROPERTY, via);
    }
    public Byte getVia() {
        return (Byte)readProperty(VIA_PROPERTY);
    }

    public void setAlertGroup(GroupOfUsers alertGroup) {
        setToOneTarget(ALERT_GROUP_PROPERTY, alertGroup, true);
    }

    public GroupOfUsers getAlertGroup() {
        return (GroupOfUsers)readProperty(ALERT_GROUP_PROPERTY);
    }


    public void setAlertUser(User alertUser) {
        setToOneTarget(ALERT_USER_PROPERTY, alertUser, true);
    }

    public User getAlertUser() {
        return (User)readProperty(ALERT_USER_PROPERTY);
    }


    public void setMessageAlert(Alert messageAlert) {
        setToOneTarget(MESSAGE_ALERT_PROPERTY, messageAlert, true);
    }

    public Alert getMessageAlert() {
        return (Alert)readProperty(MESSAGE_ALERT_PROPERTY);
    }


}
