package be.labo.data.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Assertion;
import be.labo.data.Place;

/**
 * Class _AssertionPlace was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AssertionPlace extends CayenneDataObject {

    public static final String SINCE_PROPERTY = "since";
    public static final String UPTO_PROPERTY = "upto";
    public static final String ASSERTION_PLACE_PROPERTY = "assertionPlace";
    public static final String PLACE_ASSERTION_PROPERTY = "placeAssertion";

    public static final String ID_PK_COLUMN = "id";

    public void setSince(Date since) {
        writeProperty(SINCE_PROPERTY, since);
    }
    public Date getSince() {
        return (Date)readProperty(SINCE_PROPERTY);
    }

    public void setUpto(Date upto) {
        writeProperty(UPTO_PROPERTY, upto);
    }
    public Date getUpto() {
        return (Date)readProperty(UPTO_PROPERTY);
    }

    public void setAssertionPlace(Place assertionPlace) {
        setToOneTarget(ASSERTION_PLACE_PROPERTY, assertionPlace, true);
    }

    public Place getAssertionPlace() {
        return (Place)readProperty(ASSERTION_PLACE_PROPERTY);
    }


    public void setPlaceAssertion(Assertion placeAssertion) {
        setToOneTarget(PLACE_ASSERTION_PROPERTY, placeAssertion, true);
    }

    public Assertion getPlaceAssertion() {
        return (Assertion)readProperty(PLACE_ASSERTION_PROPERTY);
    }


}
