package be.labo.data.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Assertion;
import be.labo.data.Machine;

/**
 * Class _AssertionMachine was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AssertionMachine extends CayenneDataObject {

    public static final String SINCE_PROPERTY = "since";
    public static final String UPTO_PROPERTY = "upto";
    public static final String CONDITION_MACHINE_PROPERTY = "conditionMachine";
    public static final String MACHINE_CONDITION_PROPERTY = "machineCondition";

    public static final String ID_PK_COLUMN = "id";

    public void setSince(Date since) {
        writeProperty(SINCE_PROPERTY, since);
    }
    public Date getSince() {
        return (Date)readProperty(SINCE_PROPERTY);
    }

    public void setUpto(Date upto) {
        writeProperty(UPTO_PROPERTY, upto);
    }
    public Date getUpto() {
        return (Date)readProperty(UPTO_PROPERTY);
    }

    public void setConditionMachine(Machine conditionMachine) {
        setToOneTarget(CONDITION_MACHINE_PROPERTY, conditionMachine, true);
    }

    public Machine getConditionMachine() {
        return (Machine)readProperty(CONDITION_MACHINE_PROPERTY);
    }


    public void setMachineCondition(Assertion machineCondition) {
        setToOneTarget(MACHINE_CONDITION_PROPERTY, machineCondition, true);
    }

    public Assertion getMachineCondition() {
        return (Assertion)readProperty(MACHINE_CONDITION_PROPERTY);
    }


}
