package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Audit;
import be.labo.data.Network;

/**
 * Class _AuditNetwork was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditNetwork extends CayenneDataObject {

    public static final String AUDITNETWORK_PROPERTY = "auditnetwork";
    public static final String NETWORKAUDIT_PROPERTY = "networkaudit";

    public static final String ID_PK_COLUMN = "id";

    public void setAuditnetwork(Network auditnetwork) {
        setToOneTarget(AUDITNETWORK_PROPERTY, auditnetwork, true);
    }

    public Network getAuditnetwork() {
        return (Network)readProperty(AUDITNETWORK_PROPERTY);
    }


    public void setNetworkaudit(Audit networkaudit) {
        setToOneTarget(NETWORKAUDIT_PROPERTY, networkaudit, true);
    }

    public Audit getNetworkaudit() {
        return (Audit)readProperty(NETWORKAUDIT_PROPERTY);
    }


}
