package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Audit;
import be.labo.data.Event;

/**
 * Class _AuditEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditEvent extends CayenneDataObject {

    public static final String AUDITEVENT_PROPERTY = "auditevent";
    public static final String EVENTAUDIT_PROPERTY = "eventaudit";

    public static final String ID_PK_COLUMN = "id";

    public void setAuditevent(Event auditevent) {
        setToOneTarget(AUDITEVENT_PROPERTY, auditevent, true);
    }

    public Event getAuditevent() {
        return (Event)readProperty(AUDITEVENT_PROPERTY);
    }


    public void setEventaudit(Audit eventaudit) {
        setToOneTarget(EVENTAUDIT_PROPERTY, eventaudit, true);
    }

    public Audit getEventaudit() {
        return (Audit)readProperty(EVENTAUDIT_PROPERTY);
    }


}
