package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Audit;
import be.labo.data.Scaling;

/**
 * Class _AuditScaling was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditScaling extends CayenneDataObject {

    public static final String AUDIT_SCALING_PROPERTY = "auditScaling";
    public static final String SCALINGAUDIT_PROPERTY = "scalingaudit";

    public static final String ID_PK_COLUMN = "id";

    public void setAuditScaling(Scaling auditScaling) {
        setToOneTarget(AUDIT_SCALING_PROPERTY, auditScaling, true);
    }

    public Scaling getAuditScaling() {
        return (Scaling)readProperty(AUDIT_SCALING_PROPERTY);
    }


    public void setScalingaudit(Audit scalingaudit) {
        setToOneTarget(SCALINGAUDIT_PROPERTY, scalingaudit, true);
    }

    public Audit getScalingaudit() {
        return (Audit)readProperty(SCALINGAUDIT_PROPERTY);
    }


}
