package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Alert;
import be.labo.data.Audit;

/**
 * Class _AuditAlert was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditAlert extends CayenneDataObject {

    public static final String ALERTAUDIT_PROPERTY = "alertaudit";
    public static final String AUDITALERT_PROPERTY = "auditalert";

    public static final String ID_PK_COLUMN = "id";

    public void setAlertaudit(Audit alertaudit) {
        setToOneTarget(ALERTAUDIT_PROPERTY, alertaudit, true);
    }

    public Audit getAlertaudit() {
        return (Audit)readProperty(ALERTAUDIT_PROPERTY);
    }


    public void setAuditalert(Alert auditalert) {
        setToOneTarget(AUDITALERT_PROPERTY, auditalert, true);
    }

    public Alert getAuditalert() {
        return (Alert)readProperty(AUDITALERT_PROPERTY);
    }


}
