package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Audit;
import be.labo.data.Measure;

/**
 * Class _AuditMeasure was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditMeasure extends CayenneDataObject {

    public static final String AUDITMEASURE_PROPERTY = "auditmeasure";
    public static final String MEASUREAUDIT_PROPERTY = "measureaudit";

    public static final String ID_PK_COLUMN = "id";

    public void setAuditmeasure(Measure auditmeasure) {
        setToOneTarget(AUDITMEASURE_PROPERTY, auditmeasure, true);
    }

    public Measure getAuditmeasure() {
        return (Measure)readProperty(AUDITMEASURE_PROPERTY);
    }


    public void setMeasureaudit(Audit measureaudit) {
        setToOneTarget(MEASUREAUDIT_PROPERTY, measureaudit, true);
    }

    public Audit getMeasureaudit() {
        return (Audit)readProperty(MEASUREAUDIT_PROPERTY);
    }


}
