package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Audit;
import be.labo.data.GroupOfUsers;

/**
 * Class _AuditGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditGroup extends CayenneDataObject {

    public static final String AUDITGROUP_PROPERTY = "auditgroup";
    public static final String GROUPAUDIT_PROPERTY = "groupaudit";

    public static final String ID_PK_COLUMN = "id";

    public void setAuditgroup(GroupOfUsers auditgroup) {
        setToOneTarget(AUDITGROUP_PROPERTY, auditgroup, true);
    }

    public GroupOfUsers getAuditgroup() {
        return (GroupOfUsers)readProperty(AUDITGROUP_PROPERTY);
    }


    public void setGroupaudit(Audit groupaudit) {
        setToOneTarget(GROUPAUDIT_PROPERTY, groupaudit, true);
    }

    public Audit getGroupaudit() {
        return (Audit)readProperty(GROUPAUDIT_PROPERTY);
    }


}
