package be.labo.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.DataType;
import be.labo.data.Measure;
import be.labo.data.NameCategory;

/**
 * Class _Category was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Category extends CayenneDataObject {

    public static final String COLOR_PROPERTY = "color";
    public static final String CATEG0_PROPERTY = "categ0";
    public static final String CATEG1_PROPERTY = "categ1";
    public static final String CATEG2_PROPERTY = "categ2";
    public static final String CATEG3_PROPERTY = "categ3";
    public static final String CATEG4_PROPERTY = "categ4";
    public static final String CATEG5_PROPERTY = "categ5";
    public static final String CATEG6_PROPERTY = "categ6";
    public static final String CATEG7_PROPERTY = "categ7";
    public static final String CATEG8_PROPERTY = "categ8";
    public static final String CATEG9_PROPERTY = "categ9";
    public static final String CATEGORY_MEASURE_PROPERTY = "categoryMeasure";
    public static final String CATEGORYNAME_PROPERTY = "categoryname";

    public static final String ID_PK_COLUMN = "id";

    public void setColor(short color) {
        writeProperty(COLOR_PROPERTY, color);
    }
    public short getColor() {
        Object value = readProperty(COLOR_PROPERTY);
        return (value != null) ? (Short) value : 0;
    }

    public void addToCateg0(DataType obj) {
        addToManyTarget(CATEG0_PROPERTY, obj, true);
    }
    public void removeFromCateg0(DataType obj) {
        removeToManyTarget(CATEG0_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg0() {
        return (List<DataType>)readProperty(CATEG0_PROPERTY);
    }


    public void addToCateg1(DataType obj) {
        addToManyTarget(CATEG1_PROPERTY, obj, true);
    }
    public void removeFromCateg1(DataType obj) {
        removeToManyTarget(CATEG1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg1() {
        return (List<DataType>)readProperty(CATEG1_PROPERTY);
    }


    public void addToCateg2(DataType obj) {
        addToManyTarget(CATEG2_PROPERTY, obj, true);
    }
    public void removeFromCateg2(DataType obj) {
        removeToManyTarget(CATEG2_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg2() {
        return (List<DataType>)readProperty(CATEG2_PROPERTY);
    }


    public void addToCateg3(DataType obj) {
        addToManyTarget(CATEG3_PROPERTY, obj, true);
    }
    public void removeFromCateg3(DataType obj) {
        removeToManyTarget(CATEG3_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg3() {
        return (List<DataType>)readProperty(CATEG3_PROPERTY);
    }


    public void addToCateg4(DataType obj) {
        addToManyTarget(CATEG4_PROPERTY, obj, true);
    }
    public void removeFromCateg4(DataType obj) {
        removeToManyTarget(CATEG4_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg4() {
        return (List<DataType>)readProperty(CATEG4_PROPERTY);
    }


    public void addToCateg5(DataType obj) {
        addToManyTarget(CATEG5_PROPERTY, obj, true);
    }
    public void removeFromCateg5(DataType obj) {
        removeToManyTarget(CATEG5_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg5() {
        return (List<DataType>)readProperty(CATEG5_PROPERTY);
    }


    public void addToCateg6(DataType obj) {
        addToManyTarget(CATEG6_PROPERTY, obj, true);
    }
    public void removeFromCateg6(DataType obj) {
        removeToManyTarget(CATEG6_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg6() {
        return (List<DataType>)readProperty(CATEG6_PROPERTY);
    }


    public void addToCateg7(DataType obj) {
        addToManyTarget(CATEG7_PROPERTY, obj, true);
    }
    public void removeFromCateg7(DataType obj) {
        removeToManyTarget(CATEG7_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg7() {
        return (List<DataType>)readProperty(CATEG7_PROPERTY);
    }


    public void addToCateg8(DataType obj) {
        addToManyTarget(CATEG8_PROPERTY, obj, true);
    }
    public void removeFromCateg8(DataType obj) {
        removeToManyTarget(CATEG8_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg8() {
        return (List<DataType>)readProperty(CATEG8_PROPERTY);
    }


    public void addToCateg9(DataType obj) {
        addToManyTarget(CATEG9_PROPERTY, obj, true);
    }
    public void removeFromCateg9(DataType obj) {
        removeToManyTarget(CATEG9_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DataType> getCateg9() {
        return (List<DataType>)readProperty(CATEG9_PROPERTY);
    }


    public void addToCategoryMeasure(Measure obj) {
        addToManyTarget(CATEGORY_MEASURE_PROPERTY, obj, true);
    }
    public void removeFromCategoryMeasure(Measure obj) {
        removeToManyTarget(CATEGORY_MEASURE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Measure> getCategoryMeasure() {
        return (List<Measure>)readProperty(CATEGORY_MEASURE_PROPERTY);
    }


    public void addToCategoryname(NameCategory obj) {
        addToManyTarget(CATEGORYNAME_PROPERTY, obj, true);
    }
    public void removeFromCategoryname(NameCategory obj) {
        removeToManyTarget(CATEGORYNAME_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NameCategory> getCategoryname() {
        return (List<NameCategory>)readProperty(CATEGORYNAME_PROPERTY);
    }


}
