package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Graphconfig;
import be.labo.data.Place;

/**
 * Class _Graphplace was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Graphplace extends CayenneDataObject {

    public static final String GRAPH_PLACE_PROPERTY = "graphPlace";
    public static final String PLACE_GRAPH_PROPERTY = "placeGraph";

    public static final String ID_PK_COLUMN = "id";

    public void setGraphPlace(Place graphPlace) {
        setToOneTarget(GRAPH_PLACE_PROPERTY, graphPlace, true);
    }

    public Place getGraphPlace() {
        return (Place)readProperty(GRAPH_PLACE_PROPERTY);
    }


    public void setPlaceGraph(Graphconfig placeGraph) {
        setToOneTarget(PLACE_GRAPH_PROPERTY, placeGraph, true);
    }

    public Graphconfig getPlaceGraph() {
        return (Graphconfig)readProperty(PLACE_GRAPH_PROPERTY);
    }


}
