package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.DataType;
import be.labo.data.Graphconfig;

/**
 * Class _GraphType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _GraphType extends CayenneDataObject {

    public static final String GRAPH_TYPE_PROPERTY = "graphType";
    public static final String TYPE_GRAPH_PROPERTY = "typeGraph";

    public static final String ID_PK_COLUMN = "id";

    public void setGraphType(DataType graphType) {
        setToOneTarget(GRAPH_TYPE_PROPERTY, graphType, true);
    }

    public DataType getGraphType() {
        return (DataType)readProperty(GRAPH_TYPE_PROPERTY);
    }


    public void setTypeGraph(Graphconfig typeGraph) {
        setToOneTarget(TYPE_GRAPH_PROPERTY, typeGraph, true);
    }

    public Graphconfig getTypeGraph() {
        return (Graphconfig)readProperty(TYPE_GRAPH_PROPERTY);
    }


}
