package be.labo.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Permission;

/**
 * Class _MetaClass was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MetaClass extends CayenneDataObject {

    public static final String DOMAIN_PROPERTY = "domain";
    public static final String IN_MENU_PROPERTY = "inMenu";
    public static final String JAVA_NAME_PROPERTY = "javaName";
    public static final String SECTION_PROPERTY = "section";
    public static final String META_PERMISSION_PROPERTY = "metaPermission";

    public static final String ID_PK_COLUMN = "id";

    public void setDomain(String domain) {
        writeProperty(DOMAIN_PROPERTY, domain);
    }
    public String getDomain() {
        return (String)readProperty(DOMAIN_PROPERTY);
    }

    public void setInMenu(Boolean inMenu) {
        writeProperty(IN_MENU_PROPERTY, inMenu);
    }
    public Boolean getInMenu() {
        return (Boolean)readProperty(IN_MENU_PROPERTY);
    }

    public void setJavaName(String javaName) {
        writeProperty(JAVA_NAME_PROPERTY, javaName);
    }
    public String getJavaName() {
        return (String)readProperty(JAVA_NAME_PROPERTY);
    }

    public void setSection(String section) {
        writeProperty(SECTION_PROPERTY, section);
    }
    public String getSection() {
        return (String)readProperty(SECTION_PROPERTY);
    }

    public void addToMetaPermission(Permission obj) {
        addToManyTarget(META_PERMISSION_PROPERTY, obj, true);
    }
    public void removeFromMetaPermission(Permission obj) {
        removeToManyTarget(META_PERMISSION_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Permission> getMetaPermission() {
        return (List<Permission>)readProperty(META_PERMISSION_PROPERTY);
    }


}
