package be.labo.data.auto;

import be.labo.data.Machine;
import be.labo.data.Names;

/**
 * Class _NameMachine was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NameMachine extends Names {

    public static final String NAME_MACHINE_PROPERTY = "nameMachine";

    public static final String ID_PK_COLUMN = "id";

    public void setNameMachine(Machine nameMachine) {
        setToOneTarget(NAME_MACHINE_PROPERTY, nameMachine, true);
    }

    public Machine getNameMachine() {
        return (Machine)readProperty(NAME_MACHINE_PROPERTY);
    }


}
