package be.labo.data.auto;

import be.labo.data.DataType;
import be.labo.data.Names;

/**
 * Class _NameType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NameType extends Names {

    public static final String NAME_TYPE_PROPERTY = "nameType";

    public static final String ID_PK_COLUMN = "id";

    public void setNameType(DataType nameType) {
        setToOneTarget(NAME_TYPE_PROPERTY, nameType, true);
    }

    public DataType getNameType() {
        return (DataType)readProperty(NAME_TYPE_PROPERTY);
    }


}
