package be.labo.data.auto;

import be.labo.data.Event;
import be.labo.data.Names;

/**
 * Class _NameEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NameEvent extends Names {

    public static final String NAME_EVENT_PROPERTY = "nameEvent";

    public static final String ID_PK_COLUMN = "id";

    public void setNameEvent(Event nameEvent) {
        setToOneTarget(NAME_EVENT_PROPERTY, nameEvent, true);
    }

    public Event getNameEvent() {
        return (Event)readProperty(NAME_EVENT_PROPERTY);
    }


}
