package be.labo.data.auto;

import be.labo.data.Imagemap;
import be.labo.data.Names;

/**
 * Class _NameImage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NameImage extends Names {

    public static final String NAME_IMAGE_PROPERTY = "nameImage";

    public static final String ID_PK_COLUMN = "id";

    public void setNameImage(Imagemap nameImage) {
        setToOneTarget(NAME_IMAGE_PROPERTY, nameImage, true);
    }

    public Imagemap getNameImage() {
        return (Imagemap)readProperty(NAME_IMAGE_PROPERTY);
    }


}
