package be.labo.data.auto;

import be.labo.data.Names;
import be.labo.data.Place;

/**
 * Class _NamePlace was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NamePlace extends Names {

    public static final String NAME_PLACE_PROPERTY = "namePlace";

    public static final String ID_PK_COLUMN = "id";

    public void setNamePlace(Place namePlace) {
        setToOneTarget(NAME_PLACE_PROPERTY, namePlace, true);
    }

    public Place getNamePlace() {
        return (Place)readProperty(NAME_PLACE_PROPERTY);
    }


}
