package be.labo.data.auto;

import be.labo.data.Measure;
import be.labo.data.Names;

/**
 * Class _NameMeasure was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NameMeasure extends Names {

    public static final String NAME_MEASURE_PROPERTY = "nameMeasure";

    public static final String ID_PK_COLUMN = "id";

    public void setNameMeasure(Measure nameMeasure) {
        setToOneTarget(NAME_MEASURE_PROPERTY, nameMeasure, true);
    }

    public Measure getNameMeasure() {
        return (Measure)readProperty(NAME_MEASURE_PROPERTY);
    }


}
