package be.labo.data.auto;

import be.labo.data.GroupOfUsers;
import be.labo.data.Names;

/**
 * Class _NameGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NameGroup extends Names {

    public static final String NAMEGROUP_PROPERTY = "namegroup";

    public static final String ID_PK_COLUMN = "id";

    public void setNamegroup(GroupOfUsers namegroup) {
        setToOneTarget(NAMEGROUP_PROPERTY, namegroup, true);
    }

    public GroupOfUsers getNamegroup() {
        return (GroupOfUsers)readProperty(NAMEGROUP_PROPERTY);
    }


}
