package be.labo.data.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Names was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Names extends CayenneDataObject {

    public static final String LANGUAGE_PROPERTY = "language";
    public static final String NAME_PROPERTY = "name";
    public static final String SINCE_PROPERTY = "since";


    public void setLanguage(String language) {
        writeProperty(LANGUAGE_PROPERTY, language);
    }
    public String getLanguage() {
        return (String)readProperty(LANGUAGE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setSince(Date since) {
        writeProperty(SINCE_PROPERTY, since);
    }
    public Date getSince() {
        return (Date)readProperty(SINCE_PROPERTY);
    }

}
