package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.GroupOfUsers;
import be.labo.data.MetaClass;

/**
 * Class _Permission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Permission extends CayenneDataObject {

    public static final String MAY_CREATE_PROPERTY = "mayCreate";
    public static final String MAY_DELETE_PROPERTY = "mayDelete";
    public static final String MAY_READ_PROPERTY = "mayRead";
    public static final String MAY_UPDATE_PROPERTY = "mayUpdate";
    public static final String SINGLE_OBJECT_PROPERTY = "singleObject";
    public static final String SINGLE_READ_PROPERTY = "singleRead";
    public static final String PERMISSION_GROUP_PROPERTY = "permissionGroup";
    public static final String PERMISSION_META_PROPERTY = "permissionMeta";

    public static final String ID_PK_COLUMN = "id";

    public void setMayCreate(Boolean mayCreate) {
        writeProperty(MAY_CREATE_PROPERTY, mayCreate);
    }
    public Boolean getMayCreate() {
        return (Boolean)readProperty(MAY_CREATE_PROPERTY);
    }

    public void setMayDelete(Boolean mayDelete) {
        writeProperty(MAY_DELETE_PROPERTY, mayDelete);
    }
    public Boolean getMayDelete() {
        return (Boolean)readProperty(MAY_DELETE_PROPERTY);
    }

    public void setMayRead(Boolean mayRead) {
        writeProperty(MAY_READ_PROPERTY, mayRead);
    }
    public Boolean getMayRead() {
        return (Boolean)readProperty(MAY_READ_PROPERTY);
    }

    public void setMayUpdate(Boolean mayUpdate) {
        writeProperty(MAY_UPDATE_PROPERTY, mayUpdate);
    }
    public Boolean getMayUpdate() {
        return (Boolean)readProperty(MAY_UPDATE_PROPERTY);
    }

    public void setSingleObject(Integer singleObject) {
        writeProperty(SINGLE_OBJECT_PROPERTY, singleObject);
    }
    public Integer getSingleObject() {
        return (Integer)readProperty(SINGLE_OBJECT_PROPERTY);
    }

    public void setSingleRead(Boolean singleRead) {
        writeProperty(SINGLE_READ_PROPERTY, singleRead);
    }
    public Boolean getSingleRead() {
        return (Boolean)readProperty(SINGLE_READ_PROPERTY);
    }

    public void setPermissionGroup(GroupOfUsers permissionGroup) {
        setToOneTarget(PERMISSION_GROUP_PROPERTY, permissionGroup, true);
    }

    public GroupOfUsers getPermissionGroup() {
        return (GroupOfUsers)readProperty(PERMISSION_GROUP_PROPERTY);
    }


    public void setPermissionMeta(MetaClass permissionMeta) {
        setToOneTarget(PERMISSION_META_PROPERTY, permissionMeta, true);
    }

    public MetaClass getPermissionMeta() {
        return (MetaClass)readProperty(PERMISSION_META_PROPERTY);
    }


}
