package be.labo.data.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Rawdata17 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Rawdata17 extends CayenneDataObject {

    public static final String AMP5V_PROPERTY = "amp5v";
    public static final String CHANNEL1OK_PROPERTY = "channel1ok";
    public static final String CHANNEL2OK_PROPERTY = "channel2ok";
    public static final String CPUMAC_PROPERTY = "cpumac";
    public static final String DOORALWAYSCLOSED_PROPERTY = "dooralwaysclosed";
    public static final String FAMILY_PROPERTY = "family";
    public static final String GSMBER_PROPERTY = "gsmber";
    public static final String GSMLAST_OK_PROPERTY = "gsmlastOk";
    public static final String GSMLASTRETRIES_PROPERTY = "gsmlastretries";
    public static final String GSMON_PROPERTY = "gsmon";
    public static final String GSMRSSI_PROPERTY = "gsmrssi";
    public static final String LED1_PROPERTY = "led1";
    public static final String LEDALWAYSOFF_PROPERTY = "ledalwaysoff";
    public static final String LIPOCHARGING_PROPERTY = "lipocharging";
    public static final String LIPOCHARGINGOK_PROPERTY = "lipochargingok";
    public static final String POWERFILTEROK_PROPERTY = "powerfilterok";
    public static final String RELAYEDGO_PROPERTY = "relayedgo";
    public static final String RELAYEDRETURN_PROPERTY = "relayedreturn";
    public static final String SENDINGWAN_PROPERTY = "sendingwan";
    public static final String SENTLAN_PROPERTY = "sentlan";
    public static final String SLOT_PROPERTY = "slot";
    public static final String SOLARPANELOK_PROPERTY = "solarpanelok";
    public static final String STRUCTID_PROPERTY = "structid";
    public static final String TEMPERATURE_PROPERTY = "temperature";
    public static final String TIMESTAMP_PROPERTY = "timestamp";
    public static final String TIMEVALIDITY_PROPERTY = "timevalidity";
    public static final String USBNOTCONNECT_PROPERTY = "usbnotconnect";
    public static final String VOLTSBATT_PROPERTY = "voltsbatt";
    public static final String VOLTSBATTOK_PROPERTY = "voltsbattok";
    public static final String VOLTSSOL_PROPERTY = "voltssol";
    public static final String WATERLEVEL_PROPERTY = "waterlevel";
    public static final String XBEEADDR_PROPERTY = "xbeeaddr";
    public static final String XBEEASSOC_PROPERTY = "xbeeassoc";
    public static final String XBEEON_PROPERTY = "xbeeon";
    public static final String XBEERSSI_PROPERTY = "xbeerssi";

    public static final String ID_PK_COLUMN = "id";

    public void setAmp5v(Short amp5v) {
        writeProperty(AMP5V_PROPERTY, amp5v);
    }
    public Short getAmp5v() {
        return (Short)readProperty(AMP5V_PROPERTY);
    }

    public void setChannel1ok(Boolean channel1ok) {
        writeProperty(CHANNEL1OK_PROPERTY, channel1ok);
    }
    public Boolean getChannel1ok() {
        return (Boolean)readProperty(CHANNEL1OK_PROPERTY);
    }

    public void setChannel2ok(Boolean channel2ok) {
        writeProperty(CHANNEL2OK_PROPERTY, channel2ok);
    }
    public Boolean getChannel2ok() {
        return (Boolean)readProperty(CHANNEL2OK_PROPERTY);
    }

    public void setCpumac(Integer cpumac) {
        writeProperty(CPUMAC_PROPERTY, cpumac);
    }
    public Integer getCpumac() {
        return (Integer)readProperty(CPUMAC_PROPERTY);
    }

    public void setDooralwaysclosed(Boolean dooralwaysclosed) {
        writeProperty(DOORALWAYSCLOSED_PROPERTY, dooralwaysclosed);
    }
    public Boolean getDooralwaysclosed() {
        return (Boolean)readProperty(DOORALWAYSCLOSED_PROPERTY);
    }

    public void setFamily(Byte family) {
        writeProperty(FAMILY_PROPERTY, family);
    }
    public Byte getFamily() {
        return (Byte)readProperty(FAMILY_PROPERTY);
    }

    public void setGsmber(Byte gsmber) {
        writeProperty(GSMBER_PROPERTY, gsmber);
    }
    public Byte getGsmber() {
        return (Byte)readProperty(GSMBER_PROPERTY);
    }

    public void setGsmlastOk(Boolean gsmlastOk) {
        writeProperty(GSMLAST_OK_PROPERTY, gsmlastOk);
    }
    public Boolean getGsmlastOk() {
        return (Boolean)readProperty(GSMLAST_OK_PROPERTY);
    }

    public void setGsmlastretries(Byte gsmlastretries) {
        writeProperty(GSMLASTRETRIES_PROPERTY, gsmlastretries);
    }
    public Byte getGsmlastretries() {
        return (Byte)readProperty(GSMLASTRETRIES_PROPERTY);
    }

    public void setGsmon(Boolean gsmon) {
        writeProperty(GSMON_PROPERTY, gsmon);
    }
    public Boolean getGsmon() {
        return (Boolean)readProperty(GSMON_PROPERTY);
    }

    public void setGsmrssi(Byte gsmrssi) {
        writeProperty(GSMRSSI_PROPERTY, gsmrssi);
    }
    public Byte getGsmrssi() {
        return (Byte)readProperty(GSMRSSI_PROPERTY);
    }

    public void setLed1(Boolean led1) {
        writeProperty(LED1_PROPERTY, led1);
    }
    public Boolean getLed1() {
        return (Boolean)readProperty(LED1_PROPERTY);
    }

    public void setLedalwaysoff(Boolean ledalwaysoff) {
        writeProperty(LEDALWAYSOFF_PROPERTY, ledalwaysoff);
    }
    public Boolean getLedalwaysoff() {
        return (Boolean)readProperty(LEDALWAYSOFF_PROPERTY);
    }

    public void setLipocharging(Boolean lipocharging) {
        writeProperty(LIPOCHARGING_PROPERTY, lipocharging);
    }
    public Boolean getLipocharging() {
        return (Boolean)readProperty(LIPOCHARGING_PROPERTY);
    }

    public void setLipochargingok(Boolean lipochargingok) {
        writeProperty(LIPOCHARGINGOK_PROPERTY, lipochargingok);
    }
    public Boolean getLipochargingok() {
        return (Boolean)readProperty(LIPOCHARGINGOK_PROPERTY);
    }

    public void setPowerfilterok(Boolean powerfilterok) {
        writeProperty(POWERFILTEROK_PROPERTY, powerfilterok);
    }
    public Boolean getPowerfilterok() {
        return (Boolean)readProperty(POWERFILTEROK_PROPERTY);
    }

    public void setRelayedgo(Boolean relayedgo) {
        writeProperty(RELAYEDGO_PROPERTY, relayedgo);
    }
    public Boolean getRelayedgo() {
        return (Boolean)readProperty(RELAYEDGO_PROPERTY);
    }

    public void setRelayedreturn(Boolean relayedreturn) {
        writeProperty(RELAYEDRETURN_PROPERTY, relayedreturn);
    }
    public Boolean getRelayedreturn() {
        return (Boolean)readProperty(RELAYEDRETURN_PROPERTY);
    }

    public void setSendingwan(Boolean sendingwan) {
        writeProperty(SENDINGWAN_PROPERTY, sendingwan);
    }
    public Boolean getSendingwan() {
        return (Boolean)readProperty(SENDINGWAN_PROPERTY);
    }

    public void setSentlan(Boolean sentlan) {
        writeProperty(SENTLAN_PROPERTY, sentlan);
    }
    public Boolean getSentlan() {
        return (Boolean)readProperty(SENTLAN_PROPERTY);
    }

    public void setSlot(Byte slot) {
        writeProperty(SLOT_PROPERTY, slot);
    }
    public Byte getSlot() {
        return (Byte)readProperty(SLOT_PROPERTY);
    }

    public void setSolarpanelok(Boolean solarpanelok) {
        writeProperty(SOLARPANELOK_PROPERTY, solarpanelok);
    }
    public Boolean getSolarpanelok() {
        return (Boolean)readProperty(SOLARPANELOK_PROPERTY);
    }

    public void setStructid(Byte structid) {
        writeProperty(STRUCTID_PROPERTY, structid);
    }
    public Byte getStructid() {
        return (Byte)readProperty(STRUCTID_PROPERTY);
    }

    public void setTemperature(Short temperature) {
        writeProperty(TEMPERATURE_PROPERTY, temperature);
    }
    public Short getTemperature() {
        return (Short)readProperty(TEMPERATURE_PROPERTY);
    }

    public void setTimestamp(Date timestamp) {
        writeProperty(TIMESTAMP_PROPERTY, timestamp);
    }
    public Date getTimestamp() {
        return (Date)readProperty(TIMESTAMP_PROPERTY);
    }

    public void setTimevalidity(Byte timevalidity) {
        writeProperty(TIMEVALIDITY_PROPERTY, timevalidity);
    }
    public Byte getTimevalidity() {
        return (Byte)readProperty(TIMEVALIDITY_PROPERTY);
    }

    public void setUsbnotconnect(Boolean usbnotconnect) {
        writeProperty(USBNOTCONNECT_PROPERTY, usbnotconnect);
    }
    public Boolean getUsbnotconnect() {
        return (Boolean)readProperty(USBNOTCONNECT_PROPERTY);
    }

    public void setVoltsbatt(Short voltsbatt) {
        writeProperty(VOLTSBATT_PROPERTY, voltsbatt);
    }
    public Short getVoltsbatt() {
        return (Short)readProperty(VOLTSBATT_PROPERTY);
    }

    public void setVoltsbattok(Boolean voltsbattok) {
        writeProperty(VOLTSBATTOK_PROPERTY, voltsbattok);
    }
    public Boolean getVoltsbattok() {
        return (Boolean)readProperty(VOLTSBATTOK_PROPERTY);
    }

    public void setVoltssol(Short voltssol) {
        writeProperty(VOLTSSOL_PROPERTY, voltssol);
    }
    public Short getVoltssol() {
        return (Short)readProperty(VOLTSSOL_PROPERTY);
    }

    public void setWaterlevel(Integer waterlevel) {
        writeProperty(WATERLEVEL_PROPERTY, waterlevel);
    }
    public Integer getWaterlevel() {
        return (Integer)readProperty(WATERLEVEL_PROPERTY);
    }

    public void setXbeeaddr(Integer xbeeaddr) {
        writeProperty(XBEEADDR_PROPERTY, xbeeaddr);
    }
    public Integer getXbeeaddr() {
        return (Integer)readProperty(XBEEADDR_PROPERTY);
    }

    public void setXbeeassoc(Boolean xbeeassoc) {
        writeProperty(XBEEASSOC_PROPERTY, xbeeassoc);
    }
    public Boolean getXbeeassoc() {
        return (Boolean)readProperty(XBEEASSOC_PROPERTY);
    }

    public void setXbeeon(Boolean xbeeon) {
        writeProperty(XBEEON_PROPERTY, xbeeon);
    }
    public Boolean getXbeeon() {
        return (Boolean)readProperty(XBEEON_PROPERTY);
    }

    public void setXbeerssi(Byte xbeerssi) {
        writeProperty(XBEERSSI_PROPERTY, xbeerssi);
    }
    public Byte getXbeerssi() {
        return (Byte)readProperty(XBEERSSI_PROPERTY);
    }

}
