package be.labo.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Machine;
import be.labo.data.RawDataFields;
import be.labo.data.RawTableField;

/**
 * Class _Rawtables was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Rawtables extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String RAWTYPE_PROPERTY = "rawtype";
    public static final String FIELDS_PROPERTY = "fields";
    public static final String RAW_TABLE_MACHINE_PROPERTY = "rawTableMachine";
    public static final String TABLE_FIELD_PROPERTY = "tableField";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setRawtype(Byte rawtype) {
        writeProperty(RAWTYPE_PROPERTY, rawtype);
    }
    public Byte getRawtype() {
        return (Byte)readProperty(RAWTYPE_PROPERTY);
    }

    public void addToFields(RawDataFields obj) {
        addToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    public void removeFromFields(RawDataFields obj) {
        removeToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RawDataFields> getFields() {
        return (List<RawDataFields>)readProperty(FIELDS_PROPERTY);
    }


    public void addToRawTableMachine(Machine obj) {
        addToManyTarget(RAW_TABLE_MACHINE_PROPERTY, obj, true);
    }
    public void removeFromRawTableMachine(Machine obj) {
        removeToManyTarget(RAW_TABLE_MACHINE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Machine> getRawTableMachine() {
        return (List<Machine>)readProperty(RAW_TABLE_MACHINE_PROPERTY);
    }


    public void addToTableField(RawTableField obj) {
        addToManyTarget(TABLE_FIELD_PROPERTY, obj, true);
    }
    public void removeFromTableField(RawTableField obj) {
        removeToManyTarget(TABLE_FIELD_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RawTableField> getTableField() {
        return (List<RawTableField>)readProperty(TABLE_FIELD_PROPERTY);
    }


}
