package be.labo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Scaling;

/**
 * Class _ScalingLine was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ScalingLine extends CayenneDataObject {

    public static final String MAX_PROPERTY = "max";
    public static final String MIN_PROPERTY = "min";
    public static final String RAWMAX_PROPERTY = "rawmax";
    public static final String RAWMIN_PROPERTY = "rawmin";
    public static final String OWNER_PROPERTY = "owner";

    public static final String ID_PK_COLUMN = "id";

    public void setMax(Double max) {
        writeProperty(MAX_PROPERTY, max);
    }
    public Double getMax() {
        return (Double)readProperty(MAX_PROPERTY);
    }

    public void setMin(Double min) {
        writeProperty(MIN_PROPERTY, min);
    }
    public Double getMin() {
        return (Double)readProperty(MIN_PROPERTY);
    }

    public void setRawmax(Double rawmax) {
        writeProperty(RAWMAX_PROPERTY, rawmax);
    }
    public Double getRawmax() {
        return (Double)readProperty(RAWMAX_PROPERTY);
    }

    public void setRawmin(Double rawmin) {
        writeProperty(RAWMIN_PROPERTY, rawmin);
    }
    public Double getRawmin() {
        return (Double)readProperty(RAWMIN_PROPERTY);
    }

    public void setOwner(Scaling owner) {
        setToOneTarget(OWNER_PROPERTY, owner, true);
    }

    public Scaling getOwner() {
        return (Scaling)readProperty(OWNER_PROPERTY);
    }


}
