package be.labo.data.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.GroupOfUsers;
import be.labo.data.User;

/**
 * Class _UserGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserGroup extends CayenneDataObject {

    public static final String AUDIT_PROPERTY = "audit";
    public static final String SINCE_PROPERTY = "since";
    public static final String UPTO_PROPERTY = "upto";
    public static final String GROUPUSER_PROPERTY = "groupuser";
    public static final String USERGROUP_PROPERTY = "usergroup";

    public static final String ID_PK_COLUMN = "id";

    public void setAudit(Integer audit) {
        writeProperty(AUDIT_PROPERTY, audit);
    }
    public Integer getAudit() {
        return (Integer)readProperty(AUDIT_PROPERTY);
    }

    public void setSince(Date since) {
        writeProperty(SINCE_PROPERTY, since);
    }
    public Date getSince() {
        return (Date)readProperty(SINCE_PROPERTY);
    }

    public void setUpto(Date upto) {
        writeProperty(UPTO_PROPERTY, upto);
    }
    public Date getUpto() {
        return (Date)readProperty(UPTO_PROPERTY);
    }

    public void setGroupuser(User groupuser) {
        setToOneTarget(GROUPUSER_PROPERTY, groupuser, true);
    }

    public User getGroupuser() {
        return (User)readProperty(GROUPUSER_PROPERTY);
    }


    public void setUsergroup(GroupOfUsers usergroup) {
        setToOneTarget(USERGROUP_PROPERTY, usergroup, true);
    }

    public GroupOfUsers getUsergroup() {
        return (GroupOfUsers)readProperty(USERGROUP_PROPERTY);
    }


}
