package be.labo.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import be.labo.data.Alert;
import be.labo.data.AlertMessage;
import be.labo.data.Audit;
import be.labo.data.AuditUser;
import be.labo.data.Graphconfig;
import be.labo.data.GroupOfUsers;
import be.labo.data.UserGroup;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String ACTIVE_PROPERTY = "active";
    public static final String ADMIN_PROPERTY = "admin";
    public static final String EMAIL_PROPERTY = "email";
    public static final String GSM_PROPERTY = "gsm";
    public static final String LANGUAGE_PROPERTY = "language";
    public static final String NAME_PROPERTY = "name";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String SLEEPBEGIN_PROPERTY = "sleepbegin";
    public static final String SLEEPEND_PROPERTY = "sleepend";
    public static final String ALERT_CLOSED_PROPERTY = "alertClosed";
    public static final String CHANGED_PROPERTY = "changed";
    public static final String GROUPS_PROPERTY = "groups";
    public static final String GROUPSMESSAGES_PROPERTY = "groupsmessages";
    public static final String USER_ALERT_MESSAGE_PROPERTY = "userAlertMessage";
    public static final String USER_GRAPH_PROPERTY = "userGraph";
    public static final String USERAUDIT_PROPERTY = "useraudit";
    public static final String USERGROUP_PROPERTY = "usergroup";

    public static final String ID_PK_COLUMN = "id";

    public void setActive(Boolean active) {
        writeProperty(ACTIVE_PROPERTY, active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty(ACTIVE_PROPERTY);
    }

    public void setAdmin(Short admin) {
        writeProperty(ADMIN_PROPERTY, admin);
    }
    public Short getAdmin() {
        return (Short)readProperty(ADMIN_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setGsm(String gsm) {
        writeProperty(GSM_PROPERTY, gsm);
    }
    public String getGsm() {
        return (String)readProperty(GSM_PROPERTY);
    }

    public void setLanguage(String language) {
        writeProperty(LANGUAGE_PROPERTY, language);
    }
    public String getLanguage() {
        return (String)readProperty(LANGUAGE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword() {
        return (String)readProperty(PASSWORD_PROPERTY);
    }

    public void setSleepbegin(Byte sleepbegin) {
        writeProperty(SLEEPBEGIN_PROPERTY, sleepbegin);
    }
    public Byte getSleepbegin() {
        return (Byte)readProperty(SLEEPBEGIN_PROPERTY);
    }

    public void setSleepend(Byte sleepend) {
        writeProperty(SLEEPEND_PROPERTY, sleepend);
    }
    public Byte getSleepend() {
        return (Byte)readProperty(SLEEPEND_PROPERTY);
    }

    public void addToAlertClosed(Alert obj) {
        addToManyTarget(ALERT_CLOSED_PROPERTY, obj, true);
    }
    public void removeFromAlertClosed(Alert obj) {
        removeToManyTarget(ALERT_CLOSED_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Alert> getAlertClosed() {
        return (List<Alert>)readProperty(ALERT_CLOSED_PROPERTY);
    }


    public void addToChanged(Audit obj) {
        addToManyTarget(CHANGED_PROPERTY, obj, true);
    }
    public void removeFromChanged(Audit obj) {
        removeToManyTarget(CHANGED_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Audit> getChanged() {
        return (List<Audit>)readProperty(CHANGED_PROPERTY);
    }


    public void addToGroups(GroupOfUsers obj) {
        addToManyTarget(GROUPS_PROPERTY, obj, true);
    }
    public void removeFromGroups(GroupOfUsers obj) {
        removeToManyTarget(GROUPS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<GroupOfUsers> getGroups() {
        return (List<GroupOfUsers>)readProperty(GROUPS_PROPERTY);
    }


    @SuppressWarnings("unchecked")
    public List<AlertMessage> getGroupsmessages() {
        return (List<AlertMessage>)readProperty(GROUPSMESSAGES_PROPERTY);
    }


    public void addToUserAlertMessage(AlertMessage obj) {
        addToManyTarget(USER_ALERT_MESSAGE_PROPERTY, obj, true);
    }
    public void removeFromUserAlertMessage(AlertMessage obj) {
        removeToManyTarget(USER_ALERT_MESSAGE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AlertMessage> getUserAlertMessage() {
        return (List<AlertMessage>)readProperty(USER_ALERT_MESSAGE_PROPERTY);
    }


    public void setUserGraph(Graphconfig userGraph) {
        setToOneTarget(USER_GRAPH_PROPERTY, userGraph, true);
    }

    public Graphconfig getUserGraph() {
        return (Graphconfig)readProperty(USER_GRAPH_PROPERTY);
    }


    public void addToUseraudit(AuditUser obj) {
        addToManyTarget(USERAUDIT_PROPERTY, obj, true);
    }
    public void removeFromUseraudit(AuditUser obj) {
        removeToManyTarget(USERAUDIT_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AuditUser> getUseraudit() {
        return (List<AuditUser>)readProperty(USERAUDIT_PROPERTY);
    }


    public void addToUsergroup(UserGroup obj) {
        addToManyTarget(USERGROUP_PROPERTY, obj, true);
    }
    public void removeFromUsergroup(UserGroup obj) {
        removeToManyTarget(USERGROUP_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UserGroup> getUsergroup() {
        return (List<UserGroup>)readProperty(USERGROUP_PROPERTY);
    }


}
